planetarium/config/routes.rb
Rails.application.routes.draw do
  resources :planets

end

planetarium/app/models/planet.rb
class Planet < ActiveRecord::Base
end

planetarium/app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
	def index
		@planets = Planet.all
	end

	def new
		@planet = Planet.new
	end

	def create
		# get data from the form
		planet_params = params.require(:planet).permit(:name, :position, :orbital_speed, :mass, :volume)
		#give the data to the model
		@planet = Planet.new(planet_params)
		#save the model
		@planet.save
		# redirect to show or index
		redirect_to @planet
	end

	def show
		@planet = Planet.find(params[:id])
	end

	def edit
		@planet = Planet.find(params[:id])

	end
	def update
		#get data from form
		planet_params = params.require(:planet).permit(:name, :position, :orbital_speed, :mass, :volume)
		#find the existing planet
		@planet = Planet.find(params[:id])
		#update the planet with new params
		@planet.update(planet_params)
		#redirect to show
		redirect_to @planet
	end
end

planetarium/app/helpers/planets_helper.rb
module PlanetsHelper
end

planetarium/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Planetarium</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

planetarium/app/views/planets/edit.html.erb
<h2>Edit Planet</h2>

<%= form_for(@planet) do |form| %>

<p>
	<%= form.label :name %><br />
	<%= form.text_field :name %>
</p>
<p>
	<%= form.label :position %><br />
	<%= form.number_field :position %>
</p>
<p>
	<%= form.label :orbital_speed %><br />
	<%= form.number_field :orbital_speed %>
</p>
<p>
	<%= form.label :volume %><br />
	<%= form.text_field :volume %>
</p>
<p>
	<%= form.label :mass %><br />
	<%= form.text_field :mass %>

</p>
<p>
	<%= form.submit %>
</p>

<% end %>

planetarium/app/views/planets/index.html.erb
<h2>Listing All Planets</h2>
<table>
	<tr>
		<th>Name</th>
		<th>Position</th>
		<th>Orbital Speed</th>
		<th>Mass</th>
		<th>Volume</th>
		<th></th>
	</tr>
	
	<% @planets.each do |planet| %>
	
	<tr>
		<td><%= planet.name %></td>
		<td><%= planet.position %></td>
		<td><%= planet.orbital_speed %></td>
		<td><%= planet.mass %></td>
		<td><%= planet.volume %></td>
		<td>
			<%= link_to "Show", planet_path(planet) %>
			<%= link_to "Edit", edit_planet_path(planet) %>
			<%= link_to "Destroy"  %>
		</td>

	</tr>

	<% end %>

</table>
<br />
<%= link_to "New Planet", new_planet_path %>

planetarium/app/views/planets/new.html.erb
<h2>New Planet</h2>

<%= form_for(@planet) do |form| %>

<p>
	<%= form.label :name %><br />
	<%= form.text_field :name %>
</p>
<p>
	<%= form.label :position %><br />
	<%= form.number_field :position %>
</p>
<p>
	<%= form.label :orbital_speed %><br />
	<%= form.number_field :orbital_speed %>
</p>
<p>
	<%= form.label :volume %><br />
	<%= form.text_field :volume %>
</p>
<p>
	<%= form.label :mass %><br />
	<%= form.text_field :mass %>

</p>
<p>
	<%= form.submit %>
</p>

<% end %>

planetarium/app/views/planets/show.html.erb
<h2>Showing a planet</h2>

<p>
<strong>Name:</strong>
<%= @planet.name %>

</p>
<p>
<strong>Position:</strong>
<%= @planet.position %>

</p>
<p>
<strong>Orbital Speed:</strong>
<%= @planet.orbital_speed %>

</p>
<p>
<strong>Mass:</strong>
<%= @planet.mass %>

</p>
<p>
<strong>Volume:</strong>
<%= @planet.volume %>

</p>
<%= link_to "Home", planets_path %>