baking-app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes

  resources :bakers
  root 'bakers#index'

end

baking-app/app/models/baker.rb
class Baker < ActiveRecord::Base
  has_many :recipes
  validates :name, presence: true
  validates :zip_code, length: { minimum: 5 }
  validates :zip_code, numericality: { only_integer: true }
end

baking-app/app/controllers/bakers_controller.rb
class BakersController < ApplicationController
  before_action :set_baker, only: [:show, :edit, :update, :destroy]

  # GET /bakers
  # GET /bakers.json
  def index
    @bakers = Baker.all
  end

  # GET /bakers/1
  # GET /bakers/1.json
  def show
  end

  # GET /bakers/new
  def new
    @baker = Baker.new
  end

  # GET /bakers/1/edit
  def edit
  end

  # POST /bakers
  # POST /bakers.json
  def create
    @baker = Baker.new(baker_params)

    respond_to do |format|
      if @baker.save
        format.html { redirect_to @baker, notice: 'Baker was successfully created.' }
        format.json { render :show, status: :created, location: @baker }
      else
        format.html { render :new }
        format.json { render json: @baker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bakers/1
  # PATCH/PUT /bakers/1.json
  def update
    respond_to do |format|
      if @baker.update(baker_params)
        format.html { redirect_to @baker, notice: 'Baker was successfully updated.' }
        format.json { render :show, status: :ok, location: @baker }
      else
        format.html { render :edit }
        format.json { render json: @baker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bakers/1
  # DELETE /bakers/1.json
  def destroy
    @baker.destroy
    respond_to do |format|
      format.html { redirect_to bakers_url, notice: 'Baker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baker
      @baker = Baker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def baker_params
      params.require(:baker).permit(:name, :cooking_school, :zip_code)
    end
end

baking-app/app/helpers/bakers_helper.rb
module BakersHelper
end

baking-app/app/views/bakers/_form.html.erb
<%= form_for(@baker) do |f| %>
  <% if @baker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@baker.errors.count, "error") %> prohibited this baker from being saved:</h2>

      <ul>
      <% @baker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cooking_school %><br>
    <%= f.check_box :cooking_school %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br>
    <%= f.number_field :zip_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

baking-app/app/views/bakers/edit.html.erb
<h1>Editing baker</h1>

<%= render 'form' %>

<%= link_to 'Show', @baker %> |
<%= link_to 'Back', bakers_path %>

baking-app/app/views/bakers/index.html.erb
<h1>Listing bakers</h1>
<div class="CSSTableGenerator" >
<table>

    <tr>
      <td>Name</td>
      <td>Cooking School</td>
      <td>Zip code</td>
      <td colspan="3"></td>
    </tr>
    <% @bakers.each do |baker| %>
      <tr>
        <td><%= baker.name %></td>
	<td><%= baker.cooking_school %></td>
        <td><%= baker.zip_code %></td>
        <td><%= link_to 'Show', baker %></td>
        <td><%= link_to 'Edit', edit_baker_path(baker) %></td>
        <td><%= link_to 'Destroy', baker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% current_user.email %>
      </tr>
    <% end %>

</table>
</div>
<br>

<%= link_to 'New Baker', new_baker_path %>

baking-app/app/views/bakers/new.html.erb
<h1>New baker</h1>

<%= render 'form' %>

<%= link_to 'Back', bakers_path %>

baking-app/app/views/bakers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @baker.name %>
</p>

<p>
  <strong>Cooking school:</strong>
  <%= @baker.cooking_school %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @baker.zip_code %>
</p>

<p>
  <strong>Recipes:</strong>
  <ul>
  <% @baker.recipes.each do |recipe| %>
    <li><%= link_to recipe.name, recipe %></li>
  <% end %>
  </ul>
</p>


<%= link_to 'Edit', edit_baker_path(@baker) %> |
<%= link_to 'Back', bakers_path %>