sexy_calculator/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :orders

   root 'orders#new'

end

sexy_calculator/app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	validates :width, :depth, :height, :distance, :additional_slack, :starting_u, :ending_u, :racks_crossed, :racks_through, :aisles,  numericality: {greater_than_or_equal_to: 0}
	def pccs
		(width*0.3)*2
	end
	def rack_u_subtotal
		if racks_crossed == 0
			subtotal = ((starting_u-ending_u) *1.75).abs
		else
			subtotal = height-(starting_u*1.75)+height-(ending_u*1.75)
		end
		subtotal
	end
	def length_in_inch
		racks_crossed*width+racks_through*depth+aisles*distance+rack_u_subtotal+pccs+additional_slack

	end
	def feet 
		(length_in_inch/12).round(1)
	end
	def meters
		(feet/3.2808).round(1)
	end
	def copper_length
		copper = 0;
		lengths = [1, 3, 5, 7]
		10.step(100, 5).each{|y| lengths.push(y)}
		
		lengths.each {|x| 
			if feet <= x 
				copper = x
				return copper
			end
			
		

		}


	end
		def fiber_length
		fiber =0;
		lengths = [1, 3, 5, 7]
		10.step(100, 5).each{|y| lengths.push(y)}
		
		lengths.each {|x| 
			if meters <= x
				fiber = x
				return fiber
			end
			
		

		}

	end
end

sexy_calculator/app/models/user.rb
class User < ActiveRecord::Base
	has_many :orders
	has_secure_password
	validates :first_name, :last_name, :email, presence: true
	validates :email, uniqueness: true
end

sexy_calculator/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :user_signed_in?
  private


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    !!current_user
  end

end

sexy_calculator/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	
	def new
		@order = Order.new
	end
	def create
		# get data from the form
		order_params = params.require(:order).permit(:width, :depth, :height, :distance, :additional_slack, :starting_u, :ending_u, :racks_crossed, :racks_through, :aisles)
		#give the data to the model
		@order = Order.new(order_params)
		@order.user = current_user
		#save the model
		if @order.save
			# redirect to show or index
			redirect_to edit_order_path(@order)
		else
			render :new
		end
	end
	def edit
		@order = Order.find(params[:id])
	end
	def update
		# get data from the form
		order_params = params.require(:order).permit(:width, :depth, :height, :distance, :additional_slack, :starting_u, :ending_u, :racks_crossed, :racks_through, :aisles)
		#give the data to the model
		@order = Order.find(params[:id])
		#save the model
		if @order.save
			# redirect to show or index
			redirect_to @order
		else
			render :edit
		end
	end
	def show
		@order = Order.find(params[:id])
	end
	def destroy
		@order = Order.find(params[:id])
		@order.destroy
		redirect_to new_order_path
	end

end

sexy_calculator/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new

	end

	def create
		user = User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id 
			redirect_to root_path, notice: "Welcome "+user.first_name 
		else
			flash.now.alert = "Invalid email and/or password"
			render :new			
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path, notice: "Signed Out"
	end

end

sexy_calculator/app/controllers/users_controller.rb
class UsersController < ApplicationController


	def new
		@user = User.new
	end

	def create
		# get data from the form
		user_params = params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
		#give the data to the model
		@user = User.new(user_params)
		#save the model
		if @user.save
		# redirect to show or index
			redirect_to root_path, notice: "Signed up Successfully!"
		else
			render :new
		end
	end

	def show
		@user = User.find(params[:id])
	end
	
end

sexy_calculator/app/helpers/application_helper.rb
module ApplicationHelper
end

sexy_calculator/app/helpers/orders_helper.rb
module OrdersHelper
end

sexy_calculator/app/helpers/sessions_helper.rb
module SessionsHelper
end

sexy_calculator/app/helpers/users_helper.rb
module UsersHelper
end

sexy_calculator/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SexyCalculator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<div id="flash-notice">
		<%= notice %>
	</div>
	<div id="flash-alert">
		<%= alert %>
	</div>

<%= yield %>

<% if user_signed_in? %>
<%= link_to "Sign Out", session_path, method: "delete" %>

<% else %>
<%= link_to "Sign Up", new_user_path %>
<%= link_to "Sign In", new_session_path %>
<% end %>


</body>
</html>

sexy_calculator/app/views/orders/_form.html.erb
<% if @order.errors.any? %>
<p>
 Order could not be saved:
 You are and idiot!
 an so am I!
  <ul>
    <% @order.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</p>  
<% end %>
<%= form_for(@order) do |form| %>
<p>
	<%= form.label "Rack Width" %><br />
	<%= form.number_field :width %>
</p>
<p>
	<%= form.label "Rack Depth" %><br />
	<%= form.number_field :depth %>
</p>
<p>
	<%= form.label "Height of Cabel Tray from Floor" %><br />
	<%= form.number_field :height %>
</p>
<p>
	<%= form.label "Distance Between Aisles" %><br />
	<%= form.number_field :distance %>
</p>
<p>
	<%= form.label :additional_slack %><br />
	<%= form.number_field :additional_slack %>
</p>
<p>
	<%= form.label :starting_u %><br />
	<%= form.number_field :starting_u %>
</p>
<p>
	<%= form.label :ending_u %><br />
	<%= form.number_field :ending_u%>
</p>
<p>
	<%= form.label :racks_crossed%><br />
	<%= form.number_field :racks_crossed %>
</p>
<p>
	<%= form.label :racks_through %><br />
	<%= form.number_field :racks_through %>
</p>
<p>
	<%= form.label "Aisles Crossed" %><br />
	<%= form.number_field :aisles %>
</p>



<p>
	<%= form.submit %>
</p>

<% end %>
<% if user_signed_in? %>
<%= link_to "User Account", user_path(current_user) %>
<%end%>

sexy_calculator/app/views/orders/edit.html.erb
<%= render 'form' %>
<p>
<strong>Pre-Calculated Cable Slack:</strong>
<%= @order.pccs%>
</p>
<p>
<strong>Rack U Subtotal:</strong>
<%= @order.rack_u_subtotal%>
</p>
<p>
<strong>Length in Inches:</strong>
<%= @order.length_in_inch%>
</p>
<p>
<strong>Feet:</strong>
<%= @order.feet%>
</p>
<p>
<strong>Meters:</strong>
<%= @order.meters%>
</p>
<!--<strong>User:</strong>-->
<%#= @order.user.name%>
</p>

sexy_calculator/app/views/orders/new.html.erb
<%= render 'form' %>

sexy_calculator/app/views/orders/show.html.erb
<strong>Feet:</strong>
<%= @order.feet%>
</p>
<p>
<strong>Meters:</strong>
<%= @order.meters%>
</p>
<p>
<strong>Copper:</strong>
<%= @order.copper_length%>
</p>
<p>
<strong>Fiber:</strong>
<%= @order.fiber_length%>
</p>





<%= link_to "Home", new_order_path %>

sexy_calculator/app/views/users/new.html.erb
<h2>Sign Up</h2>
<% if @user.errors.any? %>
<p>
  User account could not be created<br />
  Please correct the following <%= pluralize(@user.errors.count, 'error') %>:

  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</p>  
<% end %>

<%= form_for(@user) do |form| %>

<p>
	<%= form.label :first_name %>
	<%= form.text_field :first_name %>

<p>
<p>
	<%= form.label :last_name %>
	<%= form.text_field :last_name %>

<p>
	<%= form.label :email %>
	<%= form.text_field :email %>
</p>
<p>
	<%= form.label :password %>
	<%= form.password_field :password %>
</p>
<p>
	<%= form.label :password_confirmation %><br />
	<%= form.password_field :password_confirmation %>
</p>
<p>
	<%= form.submit %>
</p>

<% end %>

sexy_calculator/app/views/users/show.html.erb
<p>
<strong>First Name:</strong>
<%= @user.first_name %>

</p>
<p>
<strong>Last Name:</strong>
<%= @user.last_name %>

</p>
<p>
<strong>Email:</strong>
<%= @user.email %>
</p>
<p>
  <strong>Orders:</strong>
  <ul>
  <% @user.orders.each do |order| %>
    <li>
      <%= link_to "Fiber Length "+order.fiber_length.to_s+" Copper Length "+order.copper_length.to_s+" Created at "+order.updated_at.to_s, order %>
    </li>
  <% end %>
  </ul>
</p>
<%= link_to "Home", new_order_path %>